/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_uart_ll.h"

static const char* CMockString_UART_LL_deinit = "UART_LL_deinit";
static const char* CMockString_UART_LL_get_dma_position = "UART_LL_get_dma_position";
static const char* CMockString_UART_LL_init = "UART_LL_init";
static const char* CMockString_UART_LL_set_idle_callback = "UART_LL_set_idle_callback";
static const char* CMockString_UART_LL_set_rx_complete_callback = "UART_LL_set_rx_complete_callback";
static const char* CMockString_UART_LL_set_tx_complete_callback = "UART_LL_set_tx_complete_callback";
static const char* CMockString_UART_LL_start_dma_tx = "UART_LL_start_dma_tx";
static const char* CMockString_UART_LL_tx_busy = "UART_LL_tx_busy";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_bus = "bus";
static const char* CMockString_callback = "callback";
static const char* CMockString_rx_buf = "rx_buf";
static const char* CMockString_size = "size";
static const char* CMockString_sz = "sz";

typedef struct _CMOCK_UART_LL_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  UART_Bus Expected_bus;
  uint8_t* Expected_rx_buf;
  uint32_t Expected_sz;

} CMOCK_UART_LL_init_CALL_INSTANCE;

typedef struct _CMOCK_UART_LL_deinit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  UART_Bus Expected_bus;

} CMOCK_UART_LL_deinit_CALL_INSTANCE;

typedef struct _CMOCK_UART_LL_get_dma_position_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  int CallOrder;
  UART_Bus Expected_bus;

} CMOCK_UART_LL_get_dma_position_CALL_INSTANCE;

typedef struct _CMOCK_UART_LL_tx_busy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  int CallOrder;
  UART_Bus Expected_bus;

} CMOCK_UART_LL_tx_busy_CALL_INSTANCE;

typedef struct _CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  UART_Bus Expected_bus;
  uint8_t* Expected_buffer;
  uint32_t Expected_size;

} CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE;

typedef struct _CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  UART_Bus Expected_bus;
  UART_LL_TxCompleteCallback Expected_callback;

} CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE;

typedef struct _CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  UART_Bus Expected_bus;
  UART_LL_RxCompleteCallback Expected_callback;

} CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE;

typedef struct _CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  UART_Bus Expected_bus;
  UART_LL_IdleCallback Expected_callback;

} CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE;

static struct mock_uart_llInstance
{
  char UART_LL_init_IgnoreBool;
  char UART_LL_init_CallbackBool;
  CMOCK_UART_LL_init_CALLBACK UART_LL_init_CallbackFunctionPointer;
  int UART_LL_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_init_CallInstance;
  char UART_LL_deinit_IgnoreBool;
  char UART_LL_deinit_CallbackBool;
  CMOCK_UART_LL_deinit_CALLBACK UART_LL_deinit_CallbackFunctionPointer;
  int UART_LL_deinit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_deinit_CallInstance;
  char UART_LL_get_dma_position_IgnoreBool;
  uint32_t UART_LL_get_dma_position_FinalReturn;
  char UART_LL_get_dma_position_CallbackBool;
  CMOCK_UART_LL_get_dma_position_CALLBACK UART_LL_get_dma_position_CallbackFunctionPointer;
  int UART_LL_get_dma_position_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_get_dma_position_CallInstance;
  char UART_LL_tx_busy_IgnoreBool;
  bool UART_LL_tx_busy_FinalReturn;
  char UART_LL_tx_busy_CallbackBool;
  CMOCK_UART_LL_tx_busy_CALLBACK UART_LL_tx_busy_CallbackFunctionPointer;
  int UART_LL_tx_busy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_tx_busy_CallInstance;
  char UART_LL_start_dma_tx_IgnoreBool;
  char UART_LL_start_dma_tx_CallbackBool;
  CMOCK_UART_LL_start_dma_tx_CALLBACK UART_LL_start_dma_tx_CallbackFunctionPointer;
  int UART_LL_start_dma_tx_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_start_dma_tx_CallInstance;
  char UART_LL_set_tx_complete_callback_IgnoreBool;
  char UART_LL_set_tx_complete_callback_CallbackBool;
  CMOCK_UART_LL_set_tx_complete_callback_CALLBACK UART_LL_set_tx_complete_callback_CallbackFunctionPointer;
  int UART_LL_set_tx_complete_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_set_tx_complete_callback_CallInstance;
  char UART_LL_set_rx_complete_callback_IgnoreBool;
  char UART_LL_set_rx_complete_callback_CallbackBool;
  CMOCK_UART_LL_set_rx_complete_callback_CALLBACK UART_LL_set_rx_complete_callback_CallbackFunctionPointer;
  int UART_LL_set_rx_complete_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_set_rx_complete_callback_CallInstance;
  char UART_LL_set_idle_callback_IgnoreBool;
  char UART_LL_set_idle_callback_CallbackBool;
  CMOCK_UART_LL_set_idle_callback_CALLBACK UART_LL_set_idle_callback_CallbackFunctionPointer;
  int UART_LL_set_idle_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UART_LL_set_idle_callback_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_uart_ll_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.UART_LL_init_CallInstance;
  if (Mock.UART_LL_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UART_LL_deinit_CallInstance;
  if (Mock.UART_LL_deinit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_deinit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_deinit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UART_LL_get_dma_position_CallInstance;
  if (Mock.UART_LL_get_dma_position_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_get_dma_position);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_get_dma_position_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UART_LL_tx_busy_CallInstance;
  if (Mock.UART_LL_tx_busy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_tx_busy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_tx_busy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UART_LL_start_dma_tx_CallInstance;
  if (Mock.UART_LL_start_dma_tx_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_start_dma_tx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_start_dma_tx_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UART_LL_set_tx_complete_callback_CallInstance;
  if (Mock.UART_LL_set_tx_complete_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_set_tx_complete_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_set_tx_complete_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UART_LL_set_rx_complete_callback_CallInstance;
  if (Mock.UART_LL_set_rx_complete_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_set_rx_complete_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_set_rx_complete_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.UART_LL_set_idle_callback_CallInstance;
  if (Mock.UART_LL_set_idle_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_set_idle_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.UART_LL_set_idle_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_uart_ll_Init(void)
{
  mock_uart_ll_Destroy();
}

void mock_uart_ll_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void UART_LL_init(UART_Bus bus, uint8_t* rx_buf, uint32_t sz)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_init);
  cmock_call_instance = (CMOCK_UART_LL_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_init_CallInstance);
  Mock.UART_LL_init_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_init_CallInstance);
  if (Mock.UART_LL_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UART_LL_init_CallbackBool &&
      Mock.UART_LL_init_CallbackFunctionPointer != NULL)
  {
    Mock.UART_LL_init_CallbackFunctionPointer(bus, rx_buf, sz, Mock.UART_LL_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_init,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_init,CMockString_rx_buf);
    if (cmock_call_instance->Expected_rx_buf == NULL)
      { UNITY_TEST_ASSERT_NULL(rx_buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_rx_buf, rx_buf, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_init,CMockString_sz);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_sz, sz, cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_init);
    Mock.UART_LL_init_CallbackFunctionPointer(bus, rx_buf, sz, Mock.UART_LL_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UART_LL_init(CMOCK_UART_LL_init_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, uint8_t* rx_buf, uint32_t sz);
void CMockExpectParameters_UART_LL_init(CMOCK_UART_LL_init_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, uint8_t* rx_buf, uint32_t sz)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_rx_buf = rx_buf;
  cmock_call_instance->Expected_sz = sz;
}

void UART_LL_init_CMockIgnore(void)
{
  Mock.UART_LL_init_IgnoreBool = (char)1;
}

void UART_LL_init_CMockStopIgnore(void)
{
  Mock.UART_LL_init_IgnoreBool = (char)0;
}

void UART_LL_init_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_Bus bus, uint8_t* rx_buf, uint32_t sz)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_init_CALL_INSTANCE));
  CMOCK_UART_LL_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_init_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_init_CallInstance, cmock_guts_index);
  Mock.UART_LL_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_init(cmock_call_instance, bus, rx_buf, sz);
}

void UART_LL_init_AddCallback(CMOCK_UART_LL_init_CALLBACK Callback)
{
  Mock.UART_LL_init_IgnoreBool = (char)0;
  Mock.UART_LL_init_CallbackBool = (char)1;
  Mock.UART_LL_init_CallbackFunctionPointer = Callback;
}

void UART_LL_init_Stub(CMOCK_UART_LL_init_CALLBACK Callback)
{
  Mock.UART_LL_init_IgnoreBool = (char)0;
  Mock.UART_LL_init_CallbackBool = (char)0;
  Mock.UART_LL_init_CallbackFunctionPointer = Callback;
}

void UART_LL_deinit(UART_Bus bus)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_deinit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_deinit);
  cmock_call_instance = (CMOCK_UART_LL_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_deinit_CallInstance);
  Mock.UART_LL_deinit_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_deinit_CallInstance);
  if (Mock.UART_LL_deinit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UART_LL_deinit_CallbackBool &&
      Mock.UART_LL_deinit_CallbackFunctionPointer != NULL)
  {
    Mock.UART_LL_deinit_CallbackFunctionPointer(bus, Mock.UART_LL_deinit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_deinit,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_deinit_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_deinit);
    Mock.UART_LL_deinit_CallbackFunctionPointer(bus, Mock.UART_LL_deinit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UART_LL_deinit(CMOCK_UART_LL_deinit_CALL_INSTANCE* cmock_call_instance, UART_Bus bus);
void CMockExpectParameters_UART_LL_deinit(CMOCK_UART_LL_deinit_CALL_INSTANCE* cmock_call_instance, UART_Bus bus)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
}

void UART_LL_deinit_CMockIgnore(void)
{
  Mock.UART_LL_deinit_IgnoreBool = (char)1;
}

void UART_LL_deinit_CMockStopIgnore(void)
{
  Mock.UART_LL_deinit_IgnoreBool = (char)0;
}

void UART_LL_deinit_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_Bus bus)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_deinit_CALL_INSTANCE));
  CMOCK_UART_LL_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_deinit_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_deinit_CallInstance, cmock_guts_index);
  Mock.UART_LL_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_deinit(cmock_call_instance, bus);
}

void UART_LL_deinit_AddCallback(CMOCK_UART_LL_deinit_CALLBACK Callback)
{
  Mock.UART_LL_deinit_IgnoreBool = (char)0;
  Mock.UART_LL_deinit_CallbackBool = (char)1;
  Mock.UART_LL_deinit_CallbackFunctionPointer = Callback;
}

void UART_LL_deinit_Stub(CMOCK_UART_LL_deinit_CALLBACK Callback)
{
  Mock.UART_LL_deinit_IgnoreBool = (char)0;
  Mock.UART_LL_deinit_CallbackBool = (char)0;
  Mock.UART_LL_deinit_CallbackFunctionPointer = Callback;
}

uint32_t UART_LL_get_dma_position(UART_Bus bus)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_get_dma_position_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_get_dma_position);
  cmock_call_instance = (CMOCK_UART_LL_get_dma_position_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_get_dma_position_CallInstance);
  Mock.UART_LL_get_dma_position_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_get_dma_position_CallInstance);
  if (Mock.UART_LL_get_dma_position_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.UART_LL_get_dma_position_FinalReturn;
    Mock.UART_LL_get_dma_position_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.UART_LL_get_dma_position_CallbackBool &&
      Mock.UART_LL_get_dma_position_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.UART_LL_get_dma_position_CallbackFunctionPointer(bus, Mock.UART_LL_get_dma_position_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_get_dma_position,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_get_dma_position_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_get_dma_position);
    cmock_call_instance->ReturnVal = Mock.UART_LL_get_dma_position_CallbackFunctionPointer(bus, Mock.UART_LL_get_dma_position_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_UART_LL_get_dma_position(CMOCK_UART_LL_get_dma_position_CALL_INSTANCE* cmock_call_instance, UART_Bus bus);
void CMockExpectParameters_UART_LL_get_dma_position(CMOCK_UART_LL_get_dma_position_CALL_INSTANCE* cmock_call_instance, UART_Bus bus)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
}

void UART_LL_get_dma_position_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_get_dma_position_CALL_INSTANCE));
  CMOCK_UART_LL_get_dma_position_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_get_dma_position_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_get_dma_position_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_get_dma_position_CallInstance, cmock_guts_index);
  Mock.UART_LL_get_dma_position_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.UART_LL_get_dma_position_IgnoreBool = (char)1;
}

void UART_LL_get_dma_position_CMockStopIgnore(void)
{
  if(Mock.UART_LL_get_dma_position_IgnoreBool)
    Mock.UART_LL_get_dma_position_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_get_dma_position_CallInstance);
  Mock.UART_LL_get_dma_position_IgnoreBool = (char)0;
}

void UART_LL_get_dma_position_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Bus bus, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_get_dma_position_CALL_INSTANCE));
  CMOCK_UART_LL_get_dma_position_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_get_dma_position_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_get_dma_position_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_get_dma_position_CallInstance, cmock_guts_index);
  Mock.UART_LL_get_dma_position_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_get_dma_position(cmock_call_instance, bus);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void UART_LL_get_dma_position_AddCallback(CMOCK_UART_LL_get_dma_position_CALLBACK Callback)
{
  Mock.UART_LL_get_dma_position_IgnoreBool = (char)0;
  Mock.UART_LL_get_dma_position_CallbackBool = (char)1;
  Mock.UART_LL_get_dma_position_CallbackFunctionPointer = Callback;
}

void UART_LL_get_dma_position_Stub(CMOCK_UART_LL_get_dma_position_CALLBACK Callback)
{
  Mock.UART_LL_get_dma_position_IgnoreBool = (char)0;
  Mock.UART_LL_get_dma_position_CallbackBool = (char)0;
  Mock.UART_LL_get_dma_position_CallbackFunctionPointer = Callback;
}

bool UART_LL_tx_busy(UART_Bus bus)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_tx_busy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_tx_busy);
  cmock_call_instance = (CMOCK_UART_LL_tx_busy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_tx_busy_CallInstance);
  Mock.UART_LL_tx_busy_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_tx_busy_CallInstance);
  if (Mock.UART_LL_tx_busy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.UART_LL_tx_busy_FinalReturn;
    Mock.UART_LL_tx_busy_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.UART_LL_tx_busy_CallbackBool &&
      Mock.UART_LL_tx_busy_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.UART_LL_tx_busy_CallbackFunctionPointer(bus, Mock.UART_LL_tx_busy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_tx_busy,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_tx_busy_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_tx_busy);
    cmock_call_instance->ReturnVal = Mock.UART_LL_tx_busy_CallbackFunctionPointer(bus, Mock.UART_LL_tx_busy_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_UART_LL_tx_busy(CMOCK_UART_LL_tx_busy_CALL_INSTANCE* cmock_call_instance, UART_Bus bus);
void CMockExpectParameters_UART_LL_tx_busy(CMOCK_UART_LL_tx_busy_CALL_INSTANCE* cmock_call_instance, UART_Bus bus)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
}

void UART_LL_tx_busy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_tx_busy_CALL_INSTANCE));
  CMOCK_UART_LL_tx_busy_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_tx_busy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_tx_busy_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_tx_busy_CallInstance, cmock_guts_index);
  Mock.UART_LL_tx_busy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.UART_LL_tx_busy_IgnoreBool = (char)1;
}

void UART_LL_tx_busy_CMockStopIgnore(void)
{
  if(Mock.UART_LL_tx_busy_IgnoreBool)
    Mock.UART_LL_tx_busy_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_tx_busy_CallInstance);
  Mock.UART_LL_tx_busy_IgnoreBool = (char)0;
}

void UART_LL_tx_busy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_Bus bus, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_tx_busy_CALL_INSTANCE));
  CMOCK_UART_LL_tx_busy_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_tx_busy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_tx_busy_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_tx_busy_CallInstance, cmock_guts_index);
  Mock.UART_LL_tx_busy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_tx_busy(cmock_call_instance, bus);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void UART_LL_tx_busy_AddCallback(CMOCK_UART_LL_tx_busy_CALLBACK Callback)
{
  Mock.UART_LL_tx_busy_IgnoreBool = (char)0;
  Mock.UART_LL_tx_busy_CallbackBool = (char)1;
  Mock.UART_LL_tx_busy_CallbackFunctionPointer = Callback;
}

void UART_LL_tx_busy_Stub(CMOCK_UART_LL_tx_busy_CALLBACK Callback)
{
  Mock.UART_LL_tx_busy_IgnoreBool = (char)0;
  Mock.UART_LL_tx_busy_CallbackBool = (char)0;
  Mock.UART_LL_tx_busy_CallbackFunctionPointer = Callback;
}

void UART_LL_start_dma_tx(UART_Bus bus, uint8_t* buffer, uint32_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_start_dma_tx);
  cmock_call_instance = (CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_start_dma_tx_CallInstance);
  Mock.UART_LL_start_dma_tx_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_start_dma_tx_CallInstance);
  if (Mock.UART_LL_start_dma_tx_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UART_LL_start_dma_tx_CallbackBool &&
      Mock.UART_LL_start_dma_tx_CallbackFunctionPointer != NULL)
  {
    Mock.UART_LL_start_dma_tx_CallbackFunctionPointer(bus, buffer, size, Mock.UART_LL_start_dma_tx_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_start_dma_tx,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_start_dma_tx,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_start_dma_tx,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_start_dma_tx_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_start_dma_tx);
    Mock.UART_LL_start_dma_tx_CallbackFunctionPointer(bus, buffer, size, Mock.UART_LL_start_dma_tx_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UART_LL_start_dma_tx(CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, uint8_t* buffer, uint32_t size);
void CMockExpectParameters_UART_LL_start_dma_tx(CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, uint8_t* buffer, uint32_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_size = size;
}

void UART_LL_start_dma_tx_CMockIgnore(void)
{
  Mock.UART_LL_start_dma_tx_IgnoreBool = (char)1;
}

void UART_LL_start_dma_tx_CMockStopIgnore(void)
{
  Mock.UART_LL_start_dma_tx_IgnoreBool = (char)0;
}

void UART_LL_start_dma_tx_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_Bus bus, uint8_t* buffer, uint32_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE));
  CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_start_dma_tx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_start_dma_tx_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_start_dma_tx_CallInstance, cmock_guts_index);
  Mock.UART_LL_start_dma_tx_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_start_dma_tx(cmock_call_instance, bus, buffer, size);
}

void UART_LL_start_dma_tx_AddCallback(CMOCK_UART_LL_start_dma_tx_CALLBACK Callback)
{
  Mock.UART_LL_start_dma_tx_IgnoreBool = (char)0;
  Mock.UART_LL_start_dma_tx_CallbackBool = (char)1;
  Mock.UART_LL_start_dma_tx_CallbackFunctionPointer = Callback;
}

void UART_LL_start_dma_tx_Stub(CMOCK_UART_LL_start_dma_tx_CALLBACK Callback)
{
  Mock.UART_LL_start_dma_tx_IgnoreBool = (char)0;
  Mock.UART_LL_start_dma_tx_CallbackBool = (char)0;
  Mock.UART_LL_start_dma_tx_CallbackFunctionPointer = Callback;
}

void UART_LL_set_tx_complete_callback(UART_Bus bus, UART_LL_TxCompleteCallback callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_set_tx_complete_callback);
  cmock_call_instance = (CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_set_tx_complete_callback_CallInstance);
  Mock.UART_LL_set_tx_complete_callback_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_set_tx_complete_callback_CallInstance);
  if (Mock.UART_LL_set_tx_complete_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UART_LL_set_tx_complete_callback_CallbackBool &&
      Mock.UART_LL_set_tx_complete_callback_CallbackFunctionPointer != NULL)
  {
    Mock.UART_LL_set_tx_complete_callback_CallbackFunctionPointer(bus, callback, Mock.UART_LL_set_tx_complete_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_set_tx_complete_callback,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_set_tx_complete_callback,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback), sizeof(UART_LL_TxCompleteCallback), cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_set_tx_complete_callback_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_set_tx_complete_callback);
    Mock.UART_LL_set_tx_complete_callback_CallbackFunctionPointer(bus, callback, Mock.UART_LL_set_tx_complete_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UART_LL_set_tx_complete_callback(CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, UART_LL_TxCompleteCallback callback);
void CMockExpectParameters_UART_LL_set_tx_complete_callback(CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, UART_LL_TxCompleteCallback callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_callback), (const void*)(&callback),
         sizeof(UART_LL_TxCompleteCallback[sizeof(callback) == sizeof(UART_LL_TxCompleteCallback) ? 1 : -1])); /* add UART_LL_TxCompleteCallback to :treat_as_array if this causes an error */
}

void UART_LL_set_tx_complete_callback_CMockIgnore(void)
{
  Mock.UART_LL_set_tx_complete_callback_IgnoreBool = (char)1;
}

void UART_LL_set_tx_complete_callback_CMockStopIgnore(void)
{
  Mock.UART_LL_set_tx_complete_callback_IgnoreBool = (char)0;
}

void UART_LL_set_tx_complete_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_Bus bus, UART_LL_TxCompleteCallback callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE));
  CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_set_tx_complete_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_set_tx_complete_callback_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_set_tx_complete_callback_CallInstance, cmock_guts_index);
  Mock.UART_LL_set_tx_complete_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_set_tx_complete_callback(cmock_call_instance, bus, callback);
}

void UART_LL_set_tx_complete_callback_AddCallback(CMOCK_UART_LL_set_tx_complete_callback_CALLBACK Callback)
{
  Mock.UART_LL_set_tx_complete_callback_IgnoreBool = (char)0;
  Mock.UART_LL_set_tx_complete_callback_CallbackBool = (char)1;
  Mock.UART_LL_set_tx_complete_callback_CallbackFunctionPointer = Callback;
}

void UART_LL_set_tx_complete_callback_Stub(CMOCK_UART_LL_set_tx_complete_callback_CALLBACK Callback)
{
  Mock.UART_LL_set_tx_complete_callback_IgnoreBool = (char)0;
  Mock.UART_LL_set_tx_complete_callback_CallbackBool = (char)0;
  Mock.UART_LL_set_tx_complete_callback_CallbackFunctionPointer = Callback;
}

void UART_LL_set_rx_complete_callback(UART_Bus bus, UART_LL_RxCompleteCallback callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_set_rx_complete_callback);
  cmock_call_instance = (CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_set_rx_complete_callback_CallInstance);
  Mock.UART_LL_set_rx_complete_callback_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_set_rx_complete_callback_CallInstance);
  if (Mock.UART_LL_set_rx_complete_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UART_LL_set_rx_complete_callback_CallbackBool &&
      Mock.UART_LL_set_rx_complete_callback_CallbackFunctionPointer != NULL)
  {
    Mock.UART_LL_set_rx_complete_callback_CallbackFunctionPointer(bus, callback, Mock.UART_LL_set_rx_complete_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_set_rx_complete_callback,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_set_rx_complete_callback,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback), sizeof(UART_LL_RxCompleteCallback), cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_set_rx_complete_callback_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_set_rx_complete_callback);
    Mock.UART_LL_set_rx_complete_callback_CallbackFunctionPointer(bus, callback, Mock.UART_LL_set_rx_complete_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UART_LL_set_rx_complete_callback(CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, UART_LL_RxCompleteCallback callback);
void CMockExpectParameters_UART_LL_set_rx_complete_callback(CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, UART_LL_RxCompleteCallback callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_callback), (const void*)(&callback),
         sizeof(UART_LL_RxCompleteCallback[sizeof(callback) == sizeof(UART_LL_RxCompleteCallback) ? 1 : -1])); /* add UART_LL_RxCompleteCallback to :treat_as_array if this causes an error */
}

void UART_LL_set_rx_complete_callback_CMockIgnore(void)
{
  Mock.UART_LL_set_rx_complete_callback_IgnoreBool = (char)1;
}

void UART_LL_set_rx_complete_callback_CMockStopIgnore(void)
{
  Mock.UART_LL_set_rx_complete_callback_IgnoreBool = (char)0;
}

void UART_LL_set_rx_complete_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_Bus bus, UART_LL_RxCompleteCallback callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE));
  CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_set_rx_complete_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_set_rx_complete_callback_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_set_rx_complete_callback_CallInstance, cmock_guts_index);
  Mock.UART_LL_set_rx_complete_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_set_rx_complete_callback(cmock_call_instance, bus, callback);
}

void UART_LL_set_rx_complete_callback_AddCallback(CMOCK_UART_LL_set_rx_complete_callback_CALLBACK Callback)
{
  Mock.UART_LL_set_rx_complete_callback_IgnoreBool = (char)0;
  Mock.UART_LL_set_rx_complete_callback_CallbackBool = (char)1;
  Mock.UART_LL_set_rx_complete_callback_CallbackFunctionPointer = Callback;
}

void UART_LL_set_rx_complete_callback_Stub(CMOCK_UART_LL_set_rx_complete_callback_CALLBACK Callback)
{
  Mock.UART_LL_set_rx_complete_callback_IgnoreBool = (char)0;
  Mock.UART_LL_set_rx_complete_callback_CallbackBool = (char)0;
  Mock.UART_LL_set_rx_complete_callback_CallbackFunctionPointer = Callback;
}

void UART_LL_set_idle_callback(UART_Bus bus, UART_LL_IdleCallback callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_UART_LL_set_idle_callback);
  cmock_call_instance = (CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UART_LL_set_idle_callback_CallInstance);
  Mock.UART_LL_set_idle_callback_CallInstance = CMock_Guts_MemNext(Mock.UART_LL_set_idle_callback_CallInstance);
  if (Mock.UART_LL_set_idle_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.UART_LL_set_idle_callback_CallbackBool &&
      Mock.UART_LL_set_idle_callback_CallbackFunctionPointer != NULL)
  {
    Mock.UART_LL_set_idle_callback_CallbackFunctionPointer(bus, callback, Mock.UART_LL_set_idle_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_set_idle_callback,CMockString_bus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bus), (void*)(&bus), sizeof(UART_Bus), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_UART_LL_set_idle_callback,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback), sizeof(UART_LL_IdleCallback), cmock_line, CMockStringMismatch);
  }
  if (Mock.UART_LL_set_idle_callback_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_UART_LL_set_idle_callback);
    Mock.UART_LL_set_idle_callback_CallbackFunctionPointer(bus, callback, Mock.UART_LL_set_idle_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UART_LL_set_idle_callback(CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, UART_LL_IdleCallback callback);
void CMockExpectParameters_UART_LL_set_idle_callback(CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE* cmock_call_instance, UART_Bus bus, UART_LL_IdleCallback callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_bus), (const void*)(&bus),
         sizeof(UART_Bus[sizeof(bus) == sizeof(UART_Bus) ? 1 : -1])); /* add UART_Bus to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_callback), (const void*)(&callback),
         sizeof(UART_LL_IdleCallback[sizeof(callback) == sizeof(UART_LL_IdleCallback) ? 1 : -1])); /* add UART_LL_IdleCallback to :treat_as_array if this causes an error */
}

void UART_LL_set_idle_callback_CMockIgnore(void)
{
  Mock.UART_LL_set_idle_callback_IgnoreBool = (char)1;
}

void UART_LL_set_idle_callback_CMockStopIgnore(void)
{
  Mock.UART_LL_set_idle_callback_IgnoreBool = (char)0;
}

void UART_LL_set_idle_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_Bus bus, UART_LL_IdleCallback callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE));
  CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_UART_LL_set_idle_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UART_LL_set_idle_callback_CallInstance = CMock_Guts_MemChain(Mock.UART_LL_set_idle_callback_CallInstance, cmock_guts_index);
  Mock.UART_LL_set_idle_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_UART_LL_set_idle_callback(cmock_call_instance, bus, callback);
}

void UART_LL_set_idle_callback_AddCallback(CMOCK_UART_LL_set_idle_callback_CALLBACK Callback)
{
  Mock.UART_LL_set_idle_callback_IgnoreBool = (char)0;
  Mock.UART_LL_set_idle_callback_CallbackBool = (char)1;
  Mock.UART_LL_set_idle_callback_CallbackFunctionPointer = Callback;
}

void UART_LL_set_idle_callback_Stub(CMOCK_UART_LL_set_idle_callback_CALLBACK Callback)
{
  Mock.UART_LL_set_idle_callback_IgnoreBool = (char)0;
  Mock.UART_LL_set_idle_callback_CallbackBool = (char)0;
  Mock.UART_LL_set_idle_callback_CallbackFunctionPointer = Callback;
}

