#ifndef SYSCALLS_CONFIG_H
#define SYSCALLS_CONFIG_H

#ifndef SYSCALLS_UART_BUS
// USART3 is connected to the ST-Link USB on Nucleo-H563ZI
#define SYSCALLS_UART_BUS 2
#endif

#ifndef SYSCALLS_UART_TX_BUFFER_SIZE
#define SYSCALLS_UART_TX_BUFFER_SIZE 1024
#endif

#endif // SYSCALLS_CONFIG_H
