/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
/* injected defines for unity settings, etc */
#ifndef UNITY_INCLUDE_DOUBLE
#define UNITY_INCLUDE_DOUBLE
#endif /* UNITY_INCLUDE_DOUBLE */
#ifndef UNITY_SUPPORT_64
#define UNITY_SUPPORT_64
#endif /* UNITY_SUPPORT_64 */
#include "uart.h"
#include <stdlib.h>
#include <stdbool.h>
#include "mock_uart_ll.h"

/*=======Structure Used By Test Runner=====*/
struct UnityRunTestParameters
{
  UnityTestFunction func;
  const char* name;
  UNITY_LINE_TYPE line_num;
};

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_UART_init_success(void);
extern void test_UART_init_null_rx_buffer(void);
extern void test_UART_init_null_tx_buffer(void);
extern void test_UART_init_invalid_bus(void);
extern void test_UART_get_bus_count(void);
extern void test_UART_write_with_valid_handle(void);
extern void test_UART_write_with_null_handle(void);
extern void test_UART_read_with_valid_handle(void);
extern void test_UART_read_with_null_handle(void);
extern void test_UART_rx_ready_with_valid_handle(void);
extern void test_UART_deinit_with_valid_handle(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  mock_uart_ll_Init();
}
static void CMock_Verify(void)
{
  mock_uart_ll_Verify();
}
static void CMock_Destroy(void)
{
  mock_uart_ll_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("/home/abemtk/projects/pslab-mini-firmware/tests/test_uart.c");

  int number_of_tests = 11;
  struct UnityRunTestParameters run_test_params_arr[number_of_tests];

  run_test_params_arr[0].func = test_UART_init_success;
  run_test_params_arr[0].name = "test_UART_init_success";
  run_test_params_arr[0].line_num = 33;
  run_test_params_arr[1].func = test_UART_init_null_rx_buffer;
  run_test_params_arr[1].name = "test_UART_init_null_rx_buffer";
  run_test_params_arr[1].line_num = 52;
  run_test_params_arr[2].func = test_UART_init_null_tx_buffer;
  run_test_params_arr[2].name = "test_UART_init_null_tx_buffer";
  run_test_params_arr[2].line_num = 65;
  run_test_params_arr[3].func = test_UART_init_invalid_bus;
  run_test_params_arr[3].name = "test_UART_init_invalid_bus";
  run_test_params_arr[3].line_num = 78;
  run_test_params_arr[4].func = test_UART_get_bus_count;
  run_test_params_arr[4].name = "test_UART_get_bus_count";
  run_test_params_arr[4].line_num = 91;
  run_test_params_arr[5].func = test_UART_write_with_valid_handle;
  run_test_params_arr[5].name = "test_UART_write_with_valid_handle";
  run_test_params_arr[5].line_num = 100;
  run_test_params_arr[6].func = test_UART_write_with_null_handle;
  run_test_params_arr[6].name = "test_UART_write_with_null_handle";
  run_test_params_arr[6].line_num = 128;
  run_test_params_arr[7].func = test_UART_read_with_valid_handle;
  run_test_params_arr[7].name = "test_UART_read_with_valid_handle";
  run_test_params_arr[7].line_num = 140;
  run_test_params_arr[8].func = test_UART_read_with_null_handle;
  run_test_params_arr[8].name = "test_UART_read_with_null_handle";
  run_test_params_arr[8].line_num = 165;
  run_test_params_arr[9].func = test_UART_rx_ready_with_valid_handle;
  run_test_params_arr[9].name = "test_UART_rx_ready_with_valid_handle";
  run_test_params_arr[9].line_num = 177;
  run_test_params_arr[10].func = test_UART_deinit_with_valid_handle;
  run_test_params_arr[10].name = "test_UART_deinit_with_valid_handle";
  run_test_params_arr[10].line_num = 201;

  for (int i = 0; i < number_of_tests; i++)
  {
    run_test(run_test_params_arr[i].func, run_test_params_arr[i].name, run_test_params_arr[i].line_num);
  }

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
