name: Code Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code-checks:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: format
            deps: clang-format
            target: check-format
          - name: lint
            deps: clang-tidy gcc-arm-none-eabi libnewlib-arm-none-eabi
            target: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.deps }}

      - name: Build and run ${{ matrix.name }}
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --target ${{ matrix.target }}
